# 딥러닝 개념과 활용

## 머신 러닝 : 컴퓨터 프로그램이다. 
어떠한 작업을 몇개의 클래스로 나눠서 그 클래스들을 작업하는 여러가지 경험을 통하여
컴퓨터가 배울 수 있는 프로그램이라고 정의하였다.
컴퓨터가 데이터들을 활용해서 컴퓨터 스스로가 문제를 해결하는 방법을 찾아나가 퍼포먼스를 올릴 수 있는 프로그램
ex) 로지스틱 회귀분석, 기업 평가, 기상청 정보 등..

## 딥 러닝 : 머신 러닝의 한 분야
학습하는 방식에서 차이가 난다.
기계들은 일반적으로 로우 레벨에서 하이 레벨로 증가시키면서 학습을 한다.
예를 들어서, 빛과 색 정보를 가진 사진 픽셀에서 특징들을 표상해내고, 마지막으로 조건, 특징에 맞게 분류해내고 구분한다.

## 머신러닝과 딥 러닝의 비교

### 2.1 데이터 의존도
- 딥러닝과 전통적인 머신러닝의 가장 큰 차이점은 데이터 양에 따른 성능이다.
- 딥러닝 알고리즘은 어떤 과제를 이해하기 위해서 매우 큰 데이터가 필요하기 때문에 데이터가 작을때는 성능이 잘 나오지 않으나
  데이터의 양이 커지면 성능을 계속 향상시킬 수 있음
  
### 2.2 하드웨어 의존도
- 딥러닝 알고리즘은 고사양 머신이 많은 부분을 좌지우지 됨
- 머신러닝은 저사양 머신에서도 실행이 가능
- 딥러닝 알고리즘의 요구사항은 GPU가 포함되기 때문이고, GPU는 작업에서 숫자계산을 담당함.
- 딥러닝은 많은 양의 행렬곱셈을 수행해야 하기 때문에 GPU를 사용하면 보다 효율적으로 최적화 할 수 있음.

### 2.3 Feature engineering
- Feature engineering은 데이터 복잡성을 줄이고 학습 알고리즘에서 패턴을 보다 잘 보이게 하는 과정
- 이 과정은 많은 시간과 전문가가 필요하다는 점에서 어렵고 비쌈.
- 머신러닝은 대부분의 적용된 변수(feature)는 전문가가 식별한 다음 정보 영역 및 데이터 유형별로 코딩함.
  예) 신용평가 모형 개발에서 사용되는 50여개의 변수 중 비즈니스 여건이나 금융당국에 의해 제거되어야 하는
      변수(학력, 성별 등)가 있을 수 있기 때문에 전문가가 직접 확인하고 걸러내는 작업이 필요
- 딥러닝은 high-level features를 학습하며 모든 과제에서 새로운 변수 추출이라는 작업을 줄여줌
- Convolutional Neural Network의 경우, 초기 layer에서는 이미지의 edge나 line같은 low-level features를 학습하고
  그 다음 이미지의 high-level 표현을 학습함.

### 2.4 문제 해결 접근법
- 전통적인 머신러닝 알고리즘으로 문제를 해결할 때는 주로 문제를 여러 개의 파트로 나눈 후, 각각에 대한 답을 구하고
  그 결과를 합치는 방법을 추천
- 딥러닝은 end-to-end 방식으로 문제를 해결

#### 사물인지  프로젝트의 경우,
- 머신러닝 접근 방법은 1. 사물탐지 / 2. 사물인지 2단계로 나누어 학습 함.
1. 사물탐색 : grabcout과 같은 경계탐지 알고리즘(bound box detection algorithm)을 사용하여 이미지를
              훑어보고 가능한 모든 객체를 추출
2. 사물인지 : 모든 객체들을 SVM과 같은 객체 인식 알고리즘으로 관련 객체를 인식함
- 딥러닝 접근 방법은 end-to-end 방식인 YOLO net에서 이미지를 전달하면 객체의 이름과 위치가 표시 됨.

### 2.5 실행 시간
- 딥 러닝 알고리즘은 훈련 시간이 굉장히 오래 걸림
- 딥 러닝 알고르짐은 다른 알고리즘에 비해 변수가 너무 많기 때문에 ResNet의 경우, training이 약 2주 정도 걸림
- 머신 러닝의 경우, 수초에서 수시간이면 거의 훈련이 끝남.

### 2.6 해석력
- 이 요인이 딥 러닝을 실제 실무에 쓰려 마음 먹으면 그 전에 10번 정도 고민하는 이유
- 에세이의 점수를 자동으로 매기는 과제의 경우, 딥 러닝의 성능은 사람이 한 것과 유사할 정도로 뛰어나지만 아주 치명적인 문제가 있음
  -> 왜 이 점수가 부여됐는지 알 수가 없기 때문에
- 수학적으로 딥 러닝의 어느 노드가 활성화 되었는지는 알 수 있지만 우리는 거기에 어떤 뉴련이 만들어 졌는지,
  그리고 이들 뉴련 레이어가 전체적으로 무엇을 하고 있는지 알지 못하기 때문에 해석하기 힘듦
  


## 인공신경망(Artificial Neural Network)
- 인간 뇌를 기반으로 한 추론 모델.
- 인간 뇌의 추론 모델-뉴런(neuron)
- 뉴런은 기본적인 정보처리 단위

## 인간 뇌의 특징
- 100억개의 뉴런과 각 뉴런을 연결하는 6조 개의 시냅스의 결합체
- 인간의 뇌는 현존하는 어떤 컴퓨터보다 빠르게 기능을 수행할 수 있음
- 인간의 뇌는 매우 복잡하고, 비선형적이며, 병렬적인 정보 처리 시스템으로 생각할 수 있음
- 정보는 신경망 전체에 동시에 저장되고 처리됨
- 적응성에 따라 '잘못된 답'으로 이끄는 뉴런들 사이의 연결은 약화되고,
  '올바른 답'으로 이끄는 연결은 강화됨
  
## 인간의 뇌 모델링
- 생물학적인 뇌의 뉴런과 비슷하게 모델링 함
- 인공신경망은 뉴런이라는 아주 단순하지만 내부적으로 매우 복잡하게 연결된 프로세스들로 이루어져 있음
- 뉴런은 가중치가 있는 링크들로 연결되어 있음
- 각각의 뉴런은 연결을 통해 여러 입력 신호를 받지만 출력 신호는 오직 하나만 생성
- 인공 신경망 구조
- input layer -> hidden layer1 -> hidden layer2 -> output layer


## 인공 신경망의 학습
- 신경망은 가중치를 반복적으로 조정하여 학습
- 뉴런은 링크(link)로 연결되어 있고, 각 링크에는 그와 연관된 수치적인 가중치가 있음
- 가중치는 장기 기억을 위한 기본적인 수단으로 각 뉴런 입력 강도, 즉 중요도를 표현

## 인공 신경망의 가중치 조정
- 신경망의 가중치를 초기화하고 훈련 예제들의 집합에서 해당 가중치를 갱신
- 신경망의 구조를 먼저 선택하고, 어떤 학습 알고리즘을 사용할 지 결정한 후 신경망을 훈련시킴

## 뉴런의 특징
- 입력 링크에서 여러 신호를 받아서 새로운 활성화 수준을 계산하고, 출력 링크로 출력 신호를 보냄
- 입력신호는 미가공 데이터 또는 다른 뉴런의 출력이 될 수 있음
- 출력신호는 문제의 최종적인 해(solution)가 되거나 다른 뉴런에 입력 될 수 있음
- x0(뉴런에서 나온 축색돌기) -> w0(시넵스) -> w0x0(가지돌기) --> sum(wixi)+b (뉴런) --> f(활성화함수) --> f(sum(wixi)+b) (출력용 축색돌기)

## 뉴런의 계산
- 뉴런은 전이함수, 즉 활성화 함수(activation function)을 사용
- 활성화 함수를 이용한 출력 결정 순서
    1. 뉴런은 입력 신호의 가중치 합을 계산하여 임계값과 비교
    2. 가중치 합이 임계값보다 작으면 뉴런의 출력은 -1, 같거나 크면 +1을 출력함
- 활성화 함수 ( X : 뉴런으로 돌아가는 입력의 순 가중합, xi : 입력 i의 값, wi : 입력 i의 가중치
                n : 뉴런의 입력 개수 , Y는 뉴런의 출력
= X = SUM(xiwi)(i=1~n)
= Y = {+1  if X >= θ
      {-1  if X < θ
      
## 뉴런의 출력 결정
- 활성화 함수를 부호함수를 사용하는 뉴런의 실제 출력
- ex) 계단 함수, 부호 함수, 시그모이드 함수, 선형 함수

## 단일 뉴런의 학습( 단층 퍼셉트론 )
- 퍼셉트론은 선형 결합기와 하드 리미터로 구성
- 초평면(hyperplane)으로 n차원 공간을 두 개의 결정 영역으로 나눔
- 선형 분리 함수 : sum(i=1~n)(xiwi) - θ = 0

## AND 연산자 학습(임계값 θ=0.2, 학습률 α=0.1)

AND 연산자 : 입력값 두 가지가 모두 1일 때 출력값이 1이 나오는 경우
OR  연산자 : 입력값 두 가지 중 하나라도 1이면 출력값이 1이 나오는 경우

In [4]:
import numpy as np

import tensorflow as tf

In [6]:
## x_data : 데이터
## y_data : 결과값

x_data = np.array([[0,0],[0,1],[1,0],[1,1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [1]], dtype=np.float32)

# X, Y : placeholder로 지정해서 세션을 run시킬때 입력값으로 활용할 수 있도록 함

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# W = 입력값이 (x,y)이므로 [2,1]로 설정
# b = 입력값이 하나만 필요하므로 [1]로 설정

W = tf.Variable(tf.random_normal([2,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid : tf.div(1., 1. + tf.exp(tf.matmul(X,W)))
# X, W를 matrix에 multiply하고 -b를 적용해준다.
hypothesis = tf.sigmoid(tf.matmul(X,W)-b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

Instructions for updating:
Use tf.cast instead.


In [7]:
# Accuracy computation
# True if hypothesis > 0.2 else False
# predicted(예측값)을 통하여 hypothesis가 0.2보다 크냐 작으냐에 따라 1,0으로 지정
predicted = tf.cast(hypothesis > 0.2, dtype = tf.float32)
# cast를 사용하여 예측값과 Y값이 같으면 1, 다르면 0으로 accuracy 함수 만들어줌
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 500 == 0:
            print("step :", step, "\ncost :", sess.run(cost, feed_dict={X: x_data, Y: y_data}),
                  "\nWeight :\n", sess.run(W), "\nbias :\n", sess.run(b))
            h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict = {X: x_data, Y: y_data})
            print("Hypothesis:\n", h, "\nCorrect:\n", c, "\nAccuracy: ", a)

step : 0 
cost : 0.5098366 
Weight :
 [[0.22865255]
 [0.20973209]] 
bias :
 [-0.90808624]
Hypothesis:
 [[0.71260834]
 [0.7535838 ]
 [0.7570804 ]
 [0.79355204]] 
Correct:
 [[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.75
step : 500 
cost : 0.16170466 
Weight :
 [[2.762675 ]
 [2.7590458]] 
bias :
 [0.74690866]
Hypothesis:
 [[0.3214953 ]
 [0.88206553]
 [0.8824426 ]
 [0.9916309 ]] 
Correct:
 [[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.75
step : 1000 
cost : 0.09174825 
Weight :
 [[3.9722285]
 [3.9709647]] 
bias :
 [1.444523]
Hypothesis:
 [[0.19084588]
 [0.92597485]
 [0.9260614 ]
 [0.9984969 ]] 
Correct:
 [[0.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  1.0
step : 1500 
cost : 0.063016415 
Weight :
 [[4.7600226]
 [4.7594123]] 
bias :
 [1.8683934]
Hypothesis:
 [[0.13372767]
 [0.9474007 ]
 [0.947431  ]
 [0.9995247 ]] 
Correct:
 [[0.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  1.0
step : 2000 
cost : 0.04766138 
Weight :
 [[5.3391004]
 [5.33875  ]] 
bias :
 [2.1723628]
Hypothesis:
 [[0.10225984]
 [0.95954955]
 [0.95956314]
 [0.9

## XOR using NN
XOR의 속성
- x1과 x2가 서로 다를 때만 그 결과가 1이고, 나머지 경우에는 결과값을 가짐
- 그래프로 표현했을 때 결과값 1과 0에 대해서 하나의 직선으로 정확히 나눌 수가 없음

## One logistic regression unit cannot separate XOR
XOR 문제는 단순히 하나의 모델로는 풀이가 불가능하다.
->> 여러 개를 합치게 되면 가능해진다.

In [8]:
import numpy as np
import tensorflow as tf

x_data = np.array([[0,0],[0,1],[1,0],[1,1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W = tf.Variable(tf.random_normal([2,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis using sigmoid : tf.div(1., 1. + tf.exp(tf.matmul(X,W)))
hypothesis = tf.sigmoid(tf.matmul(X,W)-b)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

# Accuracy computation
# True if hypothesis > 0.2 else False
predicted = tf.cast(hypothesis > 0.2, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 500 == 0:
            print("step :", step, "\ncost :", sess.run(cost, feed_dict={X: x_data, Y: y_data}),
                  "\nWeight :\n", sess.run(W), "\nbias :\n", sess.run(b))
            h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict = {X: x_data, Y: y_data})
            print("Hypothesis:\n", h, "\nCorrect:\n", c, "\nAccuracy: ", a)
            
            
## 즉, one logistic regression 에서는 하나의 퍼셉트론으로 문제를 해결 못함을 알 수 있다.

step : 0 
cost : 0.82376504 
Weight :
 [[ 0.49596712]
 [-0.5773657 ]] 
bias :
 [0.9428371]
Hypothesis:
 [[0.28032762]
 [0.17943165]
 [0.39010522]
 [0.2642032 ]] 
Correct:
 [[1.]
 [0.]
 [1.]
 [1.]] 
Accuracy:  0.25
step : 500 
cost : 0.6933083 
Weight :
 [[0.06732345]
 [0.01908669]] 
bias :
 [0.05124907]
Hypothesis:
 [[0.48719054]
 [0.4919601 ]
 [0.5040185 ]
 [0.50878936]] 
Correct:
 [[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.5
step : 1000 
cost : 0.6931497 
Weight :
 [[0.00710258]
 [0.00500377]] 
bias :
 [0.00717991]
Hypothesis:
 [[0.49820504]
 [0.49945596]
 [0.49998066]
 [0.5012316 ]] 
Correct:
 [[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.5
step : 1500 
cost : 0.6931472 
Weight :
 [[0.00089368]
 [0.00080233]] 
bias :
 [0.00100585]
Hypothesis:
 [[0.49974853]
 [0.49994913]
 [0.49997196]
 [0.50017256]] 
Correct:
 [[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.5
step : 2000 
cost : 0.6931472 
Weight :
 [[0.00012078]
 [0.00011681]] 
bias :
 [0.0001409]
Hypothesis:
 [[0.49996477]
 [0.49999398]
 [0.49999496]

In [11]:
## 그래서 2개의 퍼셉트론을 사용해보자

import numpy as np
import tensorflow as tf

x_data = np.array([[0,0],[0,1],[1,0],[1,1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
W1 = tf.Variable(tf.random_normal([2,2]), name='weight1')
b1 = tf.Variable(tf.random_normal([2]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X,W1) + b1)

W2 = tf.Variable(tf.random_normal([2,1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
# Hypothesis using sigmoid : tf.div(1., 1. + tf.exp(tf.matmul(X,W)))
hypothesis = tf.sigmoid(tf.matmul(layer1,W2) + b2)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

# Accuracy computation
# True if hypothesis > 0.2 else False
predicted = tf.cast(hypothesis > 0.2, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 500 == 0:
            print("step :", step, "\ncost :", sess.run(cost, feed_dict={X: x_data, Y: y_data}),
                  "\nWeight :\n", sess.run([W1, W2]), "\nbias :\n", sess.run([b1, b2]))
            h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict = {X: x_data, Y: y_data})
            print("Hypothesis:\n", h, "\nCorrect:\n", c, "\nAccuracy: ", a)

step : 0 
cost : 0.92540264 
Weight :
 [array([[-1.4460417 ,  0.35130438],
       [ 0.18383317,  2.5311675 ]], dtype=float32), array([[-0.49194542],
       [-0.6575601 ]], dtype=float32)] 
bias :
 [array([ 1.320458 , -0.1155914], dtype=float32), array([0.9304179], dtype=float32)]
Hypothesis:
 [[0.39313802 0.8072944 ]
 [0.21387097 0.883084  ]
 [0.39876488 0.8319189 ]
 [0.23772341 0.8909129 ]] 
Correct:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
Accuracy:  0.5
step : 500 
cost : 0.6914418 
Weight :
 [array([[-1.3426148 , -0.07969845],
       [ 0.6375534 ,  2.3076763 ]], dtype=float32), array([[-0.49194542],
       [-0.6575601 ]], dtype=float32)] 
bias :
 [array([ 1.5264686 , -0.41097993], dtype=float32), array([0.56759703], dtype=float32)]
Hypothesis:
 [[0.5517846  0.45236525]
 [0.45161116 0.47272378]
 [0.5574944  0.52586967]
 [0.45484918 0.52717537]] 
Correct:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
Accuracy:  0.5
step : 1000 
cost : 0.6831541 
Weight :
 [array([[-1.47994   , -0.19579437],
 

step : 9000 
cost : 0.035728388 
Weight :
 [array([[-6.602276 , -6.1046677],
       [ 6.856472 ,  5.812493 ]], dtype=float32), array([[-0.49194542],
       [-0.6575601 ]], dtype=float32)] 
bias :
 [array([ 3.4376528, -3.0717554], dtype=float32), array([3.5135114], dtype=float32)]
Hypothesis:
 [[0.03616178 0.03489748]
 [0.9641453  0.96583086]
 [0.9614314  0.9613677 ]
 [0.03181246 0.03065506]] 
Correct:
 [[0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]] 
Accuracy:  1.0
step : 9500 
cost : 0.032572065 
Weight :
 [array([[-6.6689377, -6.195531 ],
       [ 6.9216466,  5.9015145]], dtype=float32), array([[-0.49194542],
       [-0.6575601 ]], dtype=float32)] 
bias :
 [array([ 3.465195 , -3.1183574], dtype=float32), array([3.5959673], dtype=float32)]
Hypothesis:
 [[0.03292668 0.03186837]
 [0.96753514 0.9689472 ]
 [0.96451956 0.964468  ]
 [0.02899751 0.02802926]] 
Correct:
 [[0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]] 
Accuracy:  1.0
step : 10000 
cost : 0.029915445 
Weight :
 [array([[-6.729476 , -6.2770987],
    

In [29]:
## 퍼셉트론의 개수를 7개까지 증가시켜보자

import numpy as np
import tensorflow as tf

x_data = np.array([[0,0],[0,1],[1,0],[1,1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
W1 = tf.Variable(tf.random_normal([2,7]), name='weight1')
b1 = tf.Variable(tf.random_normal([7]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X,W1) + b1)

W2 = tf.Variable(tf.random_normal([7,1]), name='weight2')
b2 = tf.Variable(tf.random_normal([1]), name='bias2')
# Hypothesis using sigmoid : tf.div(1., 1. + tf.exp(tf.matmul(X,W)))
hypothesis = tf.sigmoid(tf.matmul(layer1,W2) + b2)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

# Accuracy computation
# True if hypothesis > 0.2 else False
predicted = tf.cast(hypothesis > 0.2, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 500 == 0:
            print("step :", step, "\ncost :", sess.run(cost, feed_dict={X: x_data, Y: y_data}),
                  "\nWeight :\n", sess.run([W1, W2]), "\nbias :\n", sess.run([b1, b2]))
            h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict = {X: x_data, Y: y_data})
            print("Hypothesis:\n", h, "\nCorrect:\n", c, "\nAccuracy: ", a)

step : 0 
cost : 1.1199081 
Weight :
 [array([[-2.113138  ,  0.13639782, -0.98433745, -0.7573919 ,  0.13736415,
        -1.9388213 ,  0.8039631 ],
       [-1.0594468 ,  2.0178287 , -0.30624238,  0.68230927, -1.726961  ,
        -0.5223404 ,  0.6694758 ]], dtype=float32), array([[-0.9251284 ],
       [-0.30094695],
       [ 1.1453488 ],
       [-0.34816572],
       [-0.35977682],
       [-0.9757601 ],
       [-0.3004992 ]], dtype=float32)] 
bias :
 [array([ 0.7939486 ,  0.7278418 ,  0.84283805, -0.26399946,  1.6558917 ,
        0.5606624 , -1.0574663 ], dtype=float32), array([-1.2030213], dtype=float32)]
Hypothesis:
 [[0.08360204]
 [0.10277629]
 [0.14111719]
 [0.14697152]] 
Correct:
 [[0.]
 [0.]
 [0.]
 [0.]] 
Accuracy:  0.5
step : 500 
cost : 0.58095217 
Weight :
 [array([[-2.647921  ,  0.29196838, -1.1832287 , -0.76764476,  0.04331074,
        -2.2657654 ,  0.839087  ],
       [-2.093061  ,  2.0214818 , -0.7035894 ,  0.6654774 , -1.7583352 ,
        -1.41439   ,  0.70378643]], dtype=fl

step : 6500 
cost : 0.014258415 
Weight :
 [array([[-5.38522   , -0.11574854, -4.0507517 , -1.2539616 , -1.3508695 ,
        -4.432354  ,  2.3116434 ],
       [-5.440084  ,  2.0543606 , -3.9099777 ,  0.5826155 , -2.0555735 ,
        -4.4424124 ,  2.0857644 ]], dtype=float32), array([[-7.851757 ],
       [-1.0391065],
       [ 7.6893516],
       [ 0.5649819],
       [ 1.9988439],
       [-5.7041693],
       [-4.04974  ]], dtype=float32)] 
bias :
 [array([ 2.0664482 ,  0.69349176,  6.015938  , -0.50827426,  2.4762132 ,
        1.5085682 , -3.3161206 ], dtype=float32), array([-1.6841218], dtype=float32)]
Hypothesis:
 [[0.01174933]
 [0.9856545 ]
 [0.9870764 ]
 [0.01760077]] 
Correct:
 [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:  1.0
step : 7000 
cost : 0.012755479 
Weight :
 [array([[-5.425422  , -0.13910693, -4.099206  , -1.2643551 , -1.3789731 ,
        -4.473919  ,  2.3499498 ],
       [-5.4824924 ,  2.0580728 , -3.9588325 ,  0.585533  , -2.0590012 ,
        -4.488159  ,  2.125271  ]], dtype=fl

In [35]:
## layer 2개 놓고 문제풀기

x_data = np.array([[0,0],[0,1],[1,0],[1,1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)
W1 = tf.Variable(tf.random_normal([2,3]), name='weight1')
b1 = tf.Variable(tf.random_normal([3]), name='bias1')
layer1 = tf.sigmoid(tf.matmul(X,W1) + b1)

W2 = tf.Variable(tf.random_normal([3,3]), name='weight2')
b2 = tf.Variable(tf.random_normal([3]), name='bias2')
layer2 = tf.sigmoid(tf.matmul(layer1,W2) + b2)

W3 = tf.Variable(tf.random_normal([3,1]), name='weight3')
b3 = tf.Variable(tf.random_normal([1]), name='bias3')
hypothesis = tf.sigmoid(tf.matmul(layer2, W3) + b3)

# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1-Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

# Accuracy computation
# True if hypothesis > 0.2 else False
predicted = tf.cast(hypothesis > 0.2, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 500 == 0:
            print("step :", step, "\ncost :", sess.run(cost, feed_dict={X: x_data, Y: y_data}),
                  "\nWeight :\n", sess.run([W1, W2]), "\nbias :\n", sess.run([b1, b2]))
            h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict = {X: x_data, Y: y_data})
            print("Hypothesis:\n", h, "\nCorrect:\n", c, "\nAccuracy: ", a)

step : 0 
cost : 0.692396 
Weight :
 [array([[ 0.044613  , -0.18088494, -0.89101404],
       [-2.0226157 ,  0.8154059 , -1.4444437 ]], dtype=float32), array([[-0.85337716, -2.1313858 , -0.7931945 ],
       [ 0.7735773 ,  0.67552716, -0.86295116],
       [ 0.37045872, -1.1534873 ,  0.7671437 ]], dtype=float32)] 
bias :
 [array([ 0.5504816 , -0.7536897 , -0.71946543], dtype=float32), array([-0.53694993, -0.35990393, -0.8781324 ], dtype=float32)]
Hypothesis:
 [[0.49054167]
 [0.5549633 ]
 [0.50552833]
 [0.5614021 ]] 
Correct:
 [[1.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  0.5
step : 500 
cost : 0.6847033 
Weight :
 [array([[ 0.38660133, -0.3390861 , -1.0882457 ],
       [-1.9355185 ,  0.8009414 , -1.6210877 ]], dtype=float32), array([[-0.8829346 , -2.083798  , -0.7974631 ],
       [ 0.79662514,  0.7135403 , -0.8463065 ],
       [ 0.53354096, -1.1900613 ,  0.8433643 ]], dtype=float32)] 
bias :
 [array([ 0.57840574, -0.75515157, -0.7102253 ], dtype=float32), array([-0.45420894, -0.38713175, -0.829808

step : 8000 
cost : 0.018461414 
Weight :
 [array([[ 4.6728606, -2.7110353, -4.420491 ],
       [-3.1035068,  4.897349 , -3.8779974]], dtype=float32), array([[-2.457233  , -7.5195374 , -0.26224995],
       [ 6.6561356 ,  3.103119  ,  0.9776851 ],
       [ 2.95367   , -2.1340911 ,  2.9728894 ]], dtype=float32)] 
bias :
 [array([0.34488362, 0.2510096 , 0.79171115], dtype=float32), array([-0.9304525,  0.1768736, -1.2949125], dtype=float32)]
Hypothesis:
 [[0.00814405]
 [0.9839584 ]
 [0.9751655 ]
 [0.0240545 ]] 
Correct:
 [[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:  1.0
step : 8500 
cost : 0.016671538 
Weight :
 [array([[ 4.7047396, -2.7389386, -4.4377146],
       [-3.1143165,  4.9409504, -3.9001014]], dtype=float32), array([[-2.4877458 , -7.584414  , -0.22276202],
       [ 6.745559  ,  3.127665  ,  1.0206227 ],
       [ 2.9667523 , -2.1410794 ,  2.9924726 ]], dtype=float32)] 
bias :
 [array([0.34973505, 0.26076606, 0.7995984 ], dtype=float32), array([-0.94409245,  0.1910265 , -1.320216  ], dtype=f